---
version: '3.8'
networks:
  default:
      name: ${NETWORK_NAME:-doma}
services:
  terraform-utils:
    image: hashicorp/terraform:${TERRAFORM_VERSION:-1.4}
    working_dir: /infra/infrastructure
    entrypoint: [""]
    volumes:
      - ~/.aws:/root/.aws:ro
      - .:/infra:rw
    environment:
      - AWS_REGION
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
  
  checkov:
    image: bridgecrew/checkov:${CHECKOV_VERSION:-2.3.6}
    working_dir: /tf
    volumes:
      - .:/tf:rw
      - ~/.ssh:/root/.ssh
    environment:
      - AWS_DEFAULT_REGION
      - AWS_SECRET_ACCESS_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SESSION_TOKEN
  
  infracost:
    image: infracost/infracost:${INFRACOST_VERSION:-0.10}
    working_dir: /tf
    volumes:
      - .:/tf:rw
      - ~/.ssh:/root/.ssh
    environment:
      - INFRACOST_API_KEY
      
  nodejs:
    image: node:18-alpine
    working_dir: /opt/app/react-app
    volumes:      
      - .:/opt/app:rw
