agents:
  queue: default

env:
  AWS_RETRY_MODE: standard
  AWS_MAX_ATTEMPTS: 10

steps:
  - label: "where are we?"
    command:
      - env | sort
  
  - label: ":terraform: Infracost Analysis"
    key: "terraform-infracost"
    command: make infracost_analyse
    agents:
      queue: deploy-dev
    plugins:
    - artifacts#v1.2.0:
            upload:
              - .infracost/*
    - seek-oss/aws-sm#v2.3.1:
        env:
          INFRACOST_API_KEY: infracost-api-key
